apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: kirro
type: Opaque
stringData:
  DATABASE_URL: "postgresql://kirro:kirro-secure-db-2024@postgres.automation.svc.cluster.local:5432/kirro"
